import FWCore.ParameterSet.Config as cms

process = cms.Process("ExREG")
process.load("Configuration.StandardSequences.Services_cff")
process.load('Configuration.Geometry.GeometryDB_cff')
process.load('Configuration/StandardSequences/MagneticField_38T_cff')
process.load('Configuration/StandardSequences/FrontierConditions_GlobalTag_cff')
process.load("Configuration.StandardSequences.Reconstruction_cff")
process.GlobalTag.globaltag = 'START53_V10::All'

process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(-1)
    )


process.source = cms.Source("PoolSource",
                            fileNames = cms.untracked.vstring(#'file:../../../outputA.root'

'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_10_1_0oD.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_11_1_jcG.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_12_1_KND.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_13_1_DSC.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_14_1_m2y.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_15_1_dm4.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_16_1_tJw.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_17_1_zvn.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_18_1_0i0.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_19_1_ppd.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_1_1_Fql.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_20_1_9Cr.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_21_1_34Z.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_22_1_UFz.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_23_1_9jl.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_24_1_5VG.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_25_1_nKM.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_26_1_KNz.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_27_1_Fgu.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_28_1_4hK.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_29_1_kvV.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_2_1_yQb.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_30_1_ffL.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_31_1_2eB.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_32_1_F0u.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_3_1_v8w.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_4_1_Z6z.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_5_1_ACZ.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_6_1_oAW.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_7_1_b1H.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_8_1_1Gr.root',
'/store/caf/user/sani/RunD_offline_hltlike_gt/outputA_9_1_3Yv.root',

    
#'/store/caf/user/sani/RunD_offline_gt/outputA_10_1_los.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_11_1_PkX.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_12_1_6Kl.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_13_1_OQP.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_14_1_xf7.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_15_1_aG6.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_16_1_kiv.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_17_1_q92.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_18_1_61j.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_19_1_scH.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_1_1_mTr.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_20_1_3jJ.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_21_1_P2n.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_22_1_kp9.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_23_1_3u3.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_24_1_1HD.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_25_1_RG3.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_26_1_zKx.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_27_1_jNe.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_28_1_jCc.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_29_1_KdV.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_2_1_R2T.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_30_1_oYx.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_31_1_Am4.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_32_1_cFC.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_3_1_aFM.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_4_1_2OH.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_5_1_Qto.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_6_1_x8w.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_7_1_kQc.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_8_1_Eju.root',
#'/store/caf/user/sani/RunD_offline_gt/outputA_9_1_4gu.root',


#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_10_1_NvZ.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_11_1_9iD.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_12_1_C43.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_13_1_FZZ.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_14_1_Fx6.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_15_1_PpI.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_16_1_qlz.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_17_1_QDG.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_18_1_78T.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_19_1_KSG.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_1_1_Zjg.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_20_1_k5J.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_21_1_06a.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_22_1_CzL.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_23_1_U6f.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_24_1_Znn.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_25_1_oPG.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_26_1_I3V.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_27_1_eVe.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_28_1_tcM.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_29_1_3L3.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_2_1_T7f.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_30_1_Hyk.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_31_1_GNG.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_32_1_NeZ.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_3_1_wsK.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_4_1_X7i.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_5_1_BUV.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_6_1_9Ri.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_7_1_Ae4.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_8_1_eyT.root',
#'/store/caf/user/sani/RunD_online_pflike_gt/outputA_9_1_uN5.root',


#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_10_1_IP4.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_11_1_Tls.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_12_1_t64.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_13_1_FhW.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_14_1_GRO.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_15_1_BiV.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_16_1_W2j.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_17_1_axj.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_18_1_meb.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_19_1_5PO.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_1_1_5T4.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_20_1_xBF.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_21_1_WF6.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_22_1_MLM.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_23_1_3ru.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_24_1_JXi.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_25_1_QVe.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_26_1_qMm.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_27_1_reJ.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_28_1_dN1.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_29_1_9Pk.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_2_1_MuO.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_30_1_QYM.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_31_1_FYf.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_32_1_fCT.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_3_1_eMG.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_4_1_f9T.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_5_1_dCF.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_6_1_q0F.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_7_1_BM9.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_8_1_Xaz.root',
#'/store/caf/user/sani/RunD_online_hltlike_gt/outputA_9_1_29y.root',

#'/store/caf/user/sani/RunD_online_gt/outputA_10_1_IFK.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_11_1_0X8.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_12_1_yrV.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_13_1_iAh.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_14_1_kg9.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_15_1_BI6.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_16_1_TxP.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_17_1_Mgr.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_18_1_mCF.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_19_1_VAl.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_1_1_9Iq.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_20_1_xK8.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_21_1_kO5.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_22_1_Brw.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_23_1_VNh.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_24_1_w0B.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_25_1_dlI.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_26_1_oXr.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_27_1_DdZ.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_28_1_J02.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_29_1_MPu.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_2_1_oMp.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_30_1_QcD.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_31_1_YD1.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_32_1_lwH.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_3_1_QGx.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_4_1_MNF.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_5_1_EaH.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_6_1_Kq5.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_7_1_Yaq.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_8_1_t2n.root',
#'/store/caf/user/sani/RunD_online_gt/outputA_9_1_ER5.root',
 
)
                            )

process.plotDistr = cms.EDAnalyzer("plotDistr",
                                   OutputFileName = cms.string("output_offline_hltlike.root"),
                                   isData = cms.bool(True),
                                   activateNewClustering = cms.bool(False),
                                   activateOldClustering = cms.bool(True),
                                   activateOffline = cms.bool(True)
                                   )
process.p = cms.Path(process.plotDistr)

                                        
